name: blog
services:
  jekyll:
    image: jekyll/jekyll:latest
    stdin_open: true
    tty: true
    command: sh -c "bundle install && bundle exec jekyll serve --watch"
    volumes:
        - .:/srv/jekyll
    ports:
        - 4000:4000