name: blog
services:
  jekyll:
    image: jekyll/jekyll:latest
    stdin_open: true
    tty: true
    command: jekyll serve --incremental --watch --force_polling
    volumes:
        - .:/srv/jekyll
    ports:
        - 4000:4000