name: Live Deployment
run-name: "${{ github.workflow }} #${{ github.run_number }}"
on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          enablement: true
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true
      - name: Build Project
        run: bundle exec jekyll b -d output
        env:
          jekyll_env: production
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          name: Output
          path: output
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: Output